name: macOS Release Build

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          set -e
          if [ -d "/Applications/Xcode_16.0.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.0.app
          elif [ -d "/Applications/Xcode_15.4.app" ]; then
            sudo xcode-select -s /Applications/Xcode_15.4.app
          else
            sudo xcode-select -s /Applications/Xcode.app
          fi
          xcodebuild -version

      - name: Build Release (no codesign)
        run: |
          set -o pipefail
          xcodebuild -project DailyWebScanner.xcodeproj \
            -scheme DailyWebScanner \
            -configuration Release \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            | tee xcodebuild-release.log

      - name: Package app
        run: |
          set -e
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -path '*/Build/Products/Release/DailyWebScanner.app' -print -quit)
          if [ -z "$APP_PATH" ]; then echo "App not found"; exit 1; fi
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" DailyWebScanner-unsigned.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DailyWebScanner-macOS-unsigned
          path: |
            DailyWebScanner-unsigned.zip
            xcodebuild-release.log
