name: macOS Debug Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          set -e
          # Try specific then fallback to default
          if [ -d "/Applications/Xcode_16.0.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.0.app
          elif [ -d "/Applications/Xcode_15.4.app" ]; then
            sudo xcode-select -s /Applications/Xcode_15.4.app
          else
            sudo xcode-select -s /Applications/Xcode.app
          fi
          xcodebuild -version
          xcodebuild -showsdks

      - name: Show project details
        run: |
          xcodebuild -list -project DailyWebScanner.xcodeproj

      - name: Build Debug (scheme first, fallback to target; no codesign)
        run: |
          set -o pipefail
          {
            xcodebuild -project DailyWebScanner.xcodeproj \
              -scheme DailyWebScanner \
              -configuration Debug \
              -destination 'platform=macOS' \
              CODE_SIGNING_ALLOWED=NO \
            || \
            xcodebuild -project DailyWebScanner.xcodeproj \
              -target DailyWebScanner \
              -configuration Debug \
              -destination 'platform=macOS' \
              CODE_SIGNING_ALLOWED=NO; \
          } | tee xcodebuild-debug.log

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-debug-log
          path: xcodebuild-debug.log


